// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OsTresMotoqueirosDoApocalipseVerde.Infrastructure.Context;

#nullable disable

namespace OsTresMotoqueirosDoApocalipseVerde.Migrations
{
    [DbContext(typeof(MottuContext))]
    [Migration("20250517024126_MottuMigration")]
    partial class MottuMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dados", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<long?>("FuncionarioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("FuncionarioIdFuncionario")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("MotoristaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MotoristaIdMotorista")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioIdFuncionario");

                    b.HasIndex("MotoristaIdMotorista");

                    b.ToTable("dados", (string)null);
                });

            modelBuilder.Entity("MotoSituacao", b =>
                {
                    b.Property<long>("MotosIdMoto")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("SituacoesIdSituacao")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("MotosIdMoto", "SituacoesIdSituacao");

                    b.HasIndex("SituacoesIdSituacao");

                    b.ToTable("MotoSituacao");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Endereco", b =>
                {
                    b.Property<long>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEndereco"));

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<long?>("FilialId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("FilialIdFilial")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Numero")
                        .HasMaxLength(4)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("FilialIdFilial");

                    b.ToTable("endereco", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", b =>
                {
                    b.Property<long>("IdFilial")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17)
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFilial"));

                    b.Property<long>("EnderecoId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NomeFilial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<long>("ResponsavelId")
                        .HasMaxLength(7)
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("IdFilial");

                    b.HasIndex("EnderecoId");

                    b.ToTable("filial", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Funcionario", b =>
                {
                    b.Property<long>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdFuncionario"));

                    b.Property<int>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("DadosId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("FilialId")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("DadosId");

                    b.HasIndex("FilialId");

                    b.ToTable("funcionario", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Modelo", b =>
                {
                    b.Property<long>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdModelo"));

                    b.Property<float>("Consumo")
                        .HasMaxLength(4)
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("Frenagem")
                        .HasMaxLength(50)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<int>("SistemaPartida")
                        .HasMaxLength(100)
                        .HasColumnType("NUMBER(10)");

                    b.Property<float>("Tanque")
                        .HasMaxLength(3)
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("TipoCombustivel")
                        .HasMaxLength(50)
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdModelo");

                    b.ToTable("modelo", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Moto", b =>
                {
                    b.Property<long>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMoto"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)");

                    b.Property<string>("Condicao")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<float>("Latitude")
                        .HasMaxLength(5)
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Longitude")
                        .HasMaxLength(5)
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<long>("ModeloId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("ModeloIdModelo")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("MotoristaId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR2(7)");

                    b.Property<long>("SetorId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("SetorIdSetor")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("IdMoto");

                    b.HasIndex("ModeloId");

                    b.HasIndex("ModeloIdModelo");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("SetorId");

                    b.HasIndex("SetorIdSetor");

                    b.ToTable("moto", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Motorista", b =>
                {
                    b.Property<long>("IdMotorista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMotorista"));

                    b.Property<long>("DadosId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Plano")
                        .HasMaxLength(20)
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdMotorista");

                    b.HasIndex("DadosId");

                    b.ToTable("motorista", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", b =>
                {
                    b.Property<long>("IdPatio")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPatio"));

                    b.Property<int>("AreaPatio")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CapacidadeMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<long>("FilialId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("TotalMotos")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdPatio");

                    b.HasIndex("FilialId");

                    b.ToTable("patio", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", b =>
                {
                    b.Property<long>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17)
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSetor"));

                    b.Property<long>("AreaSetor")
                        .HasMaxLength(5)
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("Capacidade")
                        .HasMaxLength(3)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<long>("PatioId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("PatioIdPatio")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("QuantidadeMoto")
                        .HasMaxLength(3)
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdSetor");

                    b.HasIndex("PatioId");

                    b.HasIndex("PatioIdPatio");

                    b.ToTable("setor", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Situacao", b =>
                {
                    b.Property<long>("IdSituacao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(14)
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdSituacao"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdSituacao");

                    b.ToTable("situacao", (string)null);
                });

            modelBuilder.Entity("Dados", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioIdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaIdMotorista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Motorista");
                });

            modelBuilder.Entity("MotoSituacao", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Moto", null)
                        .WithMany()
                        .HasForeignKey("MotosIdMoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Situacao", null)
                        .WithMany()
                        .HasForeignKey("SituacoesIdSituacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Endereco", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialIdFilial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Funcionario", b =>
                {
                    b.HasOne("Dados", "Dados")
                        .WithMany()
                        .HasForeignKey("DadosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", "Filial")
                        .WithMany("Funcionarios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dados");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Moto", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Modelo", null)
                        .WithMany("Motos")
                        .HasForeignKey("ModeloIdModelo");

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", null)
                        .WithMany("Motos")
                        .HasForeignKey("SetorIdSetor");

                    b.Navigation("Modelo");

                    b.Navigation("Motorista");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Motorista", b =>
                {
                    b.HasOne("Dados", "Dados")
                        .WithMany()
                        .HasForeignKey("DadosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dados");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", "Patio")
                        .WithMany()
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", null)
                        .WithMany("Setores")
                        .HasForeignKey("PatioIdPatio");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Modelo", b =>
                {
                    b.Navigation("Motos");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", b =>
                {
                    b.Navigation("Setores");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
