// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OsTresMotoqueirosDoApocalipseVerde.Infrastructure.Context;

#nullable disable

namespace OsTresMotoqueirosDoApocalipseVerde.Migrations
{
    [DbContext(typeof(MottuContext))]
    [Migration("20250518222314_MottuMigration")]
    partial class MottuMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DADOS");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("DADOS", (string)null);
                });

            modelBuilder.Entity("MotoSituacao", b =>
                {
                    b.Property<int>("MotosIdMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SituacoesIdSituacao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("MotosIdMoto", "SituacoesIdSituacao");

                    b.HasIndex("SituacoesIdSituacao");

                    b.ToTable("MotoSituacao");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEndereco"));

                    b.Property<string>("CodigoPais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<int?>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("FilialIdFilial")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Numero")
                        .HasMaxLength(4)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("FilialIdFilial");

                    b.ToTable("endereco", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", b =>
                {
                    b.Property<int>("IdFilial")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17)
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFilial"));

                    b.Property<int>("EnderecoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeFilial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<int>("ResponsavelId")
                        .HasMaxLength(7)
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdFilial");

                    b.HasIndex("EnderecoId");

                    b.ToTable("filial", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<int>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DadosId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("DadosId");

                    b.HasIndex("FilialId");

                    b.ToTable("funcionario", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"));

                    b.Property<float>("Consumo")
                        .HasMaxLength(4)
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("Frenagem")
                        .HasMaxLength(50)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)");

                    b.Property<int>("SistemaPartida")
                        .HasMaxLength(100)
                        .HasColumnType("NUMBER(10)");

                    b.Property<float>("Tanque")
                        .HasMaxLength(3)
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("TipoCombustivel")
                        .HasMaxLength(50)
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdModelo");

                    b.ToTable("modelo", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Moto", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)");

                    b.Property<string>("Condicao")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<float>("Latitude")
                        .HasMaxLength(5)
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("ModeloId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ModeloIdModelo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR2(7)");

                    b.Property<int>("SetorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SetorIdSetor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<float>("intitude")
                        .HasMaxLength(5)
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("IdMoto");

                    b.HasIndex("ModeloId");

                    b.HasIndex("ModeloIdModelo");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("SetorId");

                    b.HasIndex("SetorIdSetor");

                    b.ToTable("moto", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Motorista", b =>
                {
                    b.Property<int>("IdMotorista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MOTORISTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMotorista"));

                    b.Property<int>("DadosId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_DADOS");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PLANO");

                    b.HasKey("IdMotorista");

                    b.HasIndex("DadosId");

                    b.ToTable("MOTORISTA", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", b =>
                {
                    b.Property<int>("IdPatio")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatio"));

                    b.Property<int>("AreaPatio")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CapacidadeMoto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TotalMotos")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdPatio");

                    b.HasIndex("FilialId");

                    b.ToTable("patio", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17)
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSetor"));

                    b.Property<int>("AreaSetor")
                        .HasMaxLength(5)
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Capacidade")
                        .HasMaxLength(3)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PatioIdPatio")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantidadeMoto")
                        .HasMaxLength(3)
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdSetor");

                    b.HasIndex("PatioId");

                    b.HasIndex("PatioIdPatio");

                    b.ToTable("setor", (string)null);
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Situacao", b =>
                {
                    b.Property<int>("IdSituacao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(14)
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSituacao"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR2(250)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdSituacao");

                    b.ToTable("situacao", (string)null);
                });

            modelBuilder.Entity("MotoSituacao", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Moto", null)
                        .WithMany()
                        .HasForeignKey("MotosIdMoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Situacao", null)
                        .WithMany()
                        .HasForeignKey("SituacoesIdSituacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Endereco", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialIdFilial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Funcionario", b =>
                {
                    b.HasOne("Dados", "Dados")
                        .WithMany()
                        .HasForeignKey("DadosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", "Filial")
                        .WithMany("Funcionarios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dados");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Moto", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Modelo", null)
                        .WithMany("Motos")
                        .HasForeignKey("ModeloIdModelo");

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Motorista", "Motorista")
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", "Setor")
                        .WithMany()
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", null)
                        .WithMany("Motos")
                        .HasForeignKey("SetorIdSetor");

                    b.Navigation("Modelo");

                    b.Navigation("Motorista");

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Motorista", b =>
                {
                    b.HasOne("Dados", "Dados")
                        .WithMany()
                        .HasForeignKey("DadosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dados");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", b =>
                {
                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", "Patio")
                        .WithMany()
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", null)
                        .WithMany("Setores")
                        .HasForeignKey("PatioIdPatio");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Filial", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Modelo", b =>
                {
                    b.Navigation("Motos");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Patio", b =>
                {
                    b.Navigation("Setores");
                });

            modelBuilder.Entity("OsTresMotoqueirosDoApocalipseVerde.Domain.Entity.Setor", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
